// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Booking struct {
	ID              int64     `json:"id"`
	UserBooking     string    `json:"user_booking"`
	HomestayBooking int64     `json:"homestay_booking"`
	PromotionID     int64     `json:"promotion_id"`
	PaymentID       int64     `json:"payment_id"`
	Status          string    `json:"status"`
	BookingDate     time.Time `json:"booking_date"`
	CheckinDate     time.Time `json:"checkin_date"`
	CheckoutDate    time.Time `json:"checkout_date"`
	NumberOfGuest   int32     `json:"number_of_guest"`
	// must be positive
	ServiceFee string `json:"service_fee"`
	// must be positive
	Tax string `json:"tax"`
}

type Feedback struct {
	ID                int64     `json:"id"`
	UserComment       string    `json:"user_comment"`
	HomestayCommented int64     `json:"homestay_commented"`
	Rating            string    `json:"rating"`
	Commention        string    `json:"commention"`
	CreatedAt         time.Time `json:"created_at"`
}

type Homestay struct {
	ID          int64  `json:"id"`
	Description string `json:"description"`
	Address     string `json:"address"`
	NumberOfBed int32  `json:"number_of_bed"`
	Capacity    int32  `json:"capacity"`
	Price       string `json:"price"`
	Status      string `json:"status"`
	MainImage   string `json:"main_image"`
	FirstImage  string `json:"first_image"`
	SecondImage string `json:"second_image"`
	ThirdImage  string `json:"third_image"`
}

type Payment struct {
	ID        int64     `json:"id"`
	Amount    string    `json:"amount"`
	PayDate   time.Time `json:"pay_date"`
	PayMethod string    `json:"pay_method"`
	Status    string    `json:"status"`
}

type Promotion struct {
	ID              int64     `json:"id"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	DiscountPercent float64   `json:"discount_percent"`
	StartDate       time.Time `json:"start_date"`
	EndDate         time.Time `json:"end_date"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	Phone             string    `json:"phone"`
	Role              string    `json:"role"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
