// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: booking.sql

package db

import (
	"context"
	"time"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
  booking_id,
  user_booking,
  homestay_booking,
  promotion_id,
  status,
  booking_date,
  checkin_date,
  checkout_date,
  number_of_guest,
  service_fee,
  tax
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING booking_id, user_booking, homestay_booking, promotion_id, status, booking_date, checkin_date, checkout_date, number_of_guest, service_fee, tax
`

type CreateBookingParams struct {
	BookingID       string    `json:"booking_id"`
	UserBooking     string    `json:"user_booking"`
	HomestayBooking int64     `json:"homestay_booking"`
	PromotionID     string    `json:"promotion_id"`
	Status          string    `json:"status"`
	BookingDate     time.Time `json:"booking_date"`
	CheckinDate     time.Time `json:"checkin_date"`
	CheckoutDate    time.Time `json:"checkout_date"`
	NumberOfGuest   int32     `json:"number_of_guest"`
	ServiceFee      float64   `json:"service_fee"`
	Tax             float64   `json:"tax"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, createBooking,
		arg.BookingID,
		arg.UserBooking,
		arg.HomestayBooking,
		arg.PromotionID,
		arg.Status,
		arg.BookingDate,
		arg.CheckinDate,
		arg.CheckoutDate,
		arg.NumberOfGuest,
		arg.ServiceFee,
		arg.Tax,
	)
	var i Booking
	err := row.Scan(
		&i.BookingID,
		&i.UserBooking,
		&i.HomestayBooking,
		&i.PromotionID,
		&i.Status,
		&i.BookingDate,
		&i.CheckinDate,
		&i.CheckoutDate,
		&i.NumberOfGuest,
		&i.ServiceFee,
		&i.Tax,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM bookings WHERE booking_id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, bookingID string) error {
	_, err := q.db.ExecContext(ctx, deleteBooking, bookingID)
	return err
}

const finishBooking = `-- name: FinishBooking :one
UPDATE bookings
SET status = $2
WHERE booking_id = $1
RETURNING booking_id, user_booking, homestay_booking, promotion_id, status, booking_date, checkin_date, checkout_date, number_of_guest, service_fee, tax
`

type FinishBookingParams struct {
	BookingID string `json:"booking_id"`
	Status    string `json:"status"`
}

func (q *Queries) FinishBooking(ctx context.Context, arg FinishBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, finishBooking, arg.BookingID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.BookingID,
		&i.UserBooking,
		&i.HomestayBooking,
		&i.PromotionID,
		&i.Status,
		&i.BookingDate,
		&i.CheckinDate,
		&i.CheckoutDate,
		&i.NumberOfGuest,
		&i.ServiceFee,
		&i.Tax,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT booking_id, user_booking, homestay_booking, promotion_id, status, booking_date, checkin_date, checkout_date, number_of_guest, service_fee, tax FROM bookings
WHERE booking_id = $1 LIMIT 1
`

func (q *Queries) GetBooking(ctx context.Context, bookingID string) (Booking, error) {
	row := q.db.QueryRowContext(ctx, getBooking, bookingID)
	var i Booking
	err := row.Scan(
		&i.BookingID,
		&i.UserBooking,
		&i.HomestayBooking,
		&i.PromotionID,
		&i.Status,
		&i.BookingDate,
		&i.CheckinDate,
		&i.CheckoutDate,
		&i.NumberOfGuest,
		&i.ServiceFee,
		&i.Tax,
	)
	return i, err
}

const getBookingByHomestayAndTime = `-- name: GetBookingByHomestayAndTime :many
SELECT booking_id, user_booking, homestay_booking, promotion_id, status, booking_date, checkin_date, checkout_date, number_of_guest, service_fee, tax FROM bookings
WHERE homestay_booking = $1 
AND (
  (checkin_date >= $2 AND checkout_date <= $3)
  OR (checkin_date <= $2 AND checkout_date >= $2)
  OR (checkin_date >= $2 AND checkin_date <= $3 AND checkout_date >= $3)
  OR (checkin_date = $3)
  OR (checkout_date = $2)
)
`

type GetBookingByHomestayAndTimeParams struct {
	HomestayBooking int64     `json:"homestay_booking"`
	CheckinDate     time.Time `json:"checkin_date"`
	CheckoutDate    time.Time `json:"checkout_date"`
}

func (q *Queries) GetBookingByHomestayAndTime(ctx context.Context, arg GetBookingByHomestayAndTimeParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, getBookingByHomestayAndTime, arg.HomestayBooking, arg.CheckinDate, arg.CheckoutDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.BookingID,
			&i.UserBooking,
			&i.HomestayBooking,
			&i.PromotionID,
			&i.Status,
			&i.BookingDate,
			&i.CheckinDate,
			&i.CheckoutDate,
			&i.NumberOfGuest,
			&i.ServiceFee,
			&i.Tax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingByHomestay = `-- name: ListBookingByHomestay :many
SELECT booking_id, user_booking, homestay_booking, promotion_id, status, booking_date, checkin_date, checkout_date, number_of_guest, service_fee, tax FROM bookings
WHERE homestay_booking = $1
ORDER BY booking_id
LIMIT $2
OFFSET $3
`

type ListBookingByHomestayParams struct {
	HomestayBooking int64 `json:"homestay_booking"`
	Limit           int32 `json:"limit"`
	Offset          int32 `json:"offset"`
}

func (q *Queries) ListBookingByHomestay(ctx context.Context, arg ListBookingByHomestayParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingByHomestay, arg.HomestayBooking, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.BookingID,
			&i.UserBooking,
			&i.HomestayBooking,
			&i.PromotionID,
			&i.Status,
			&i.BookingDate,
			&i.CheckinDate,
			&i.CheckoutDate,
			&i.NumberOfGuest,
			&i.ServiceFee,
			&i.Tax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingByUser = `-- name: ListBookingByUser :many
SELECT booking_id, user_booking, homestay_booking, promotion_id, status, booking_date, checkin_date, checkout_date, number_of_guest, service_fee, tax FROM bookings
WHERE user_booking = $1
ORDER BY booking_id
LIMIT $2
OFFSET $3
`

type ListBookingByUserParams struct {
	UserBooking string `json:"user_booking"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListBookingByUser(ctx context.Context, arg ListBookingByUserParams) ([]Booking, error) {
	rows, err := q.db.QueryContext(ctx, listBookingByUser, arg.UserBooking, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.BookingID,
			&i.UserBooking,
			&i.HomestayBooking,
			&i.PromotionID,
			&i.Status,
			&i.BookingDate,
			&i.CheckinDate,
			&i.CheckoutDate,
			&i.NumberOfGuest,
			&i.ServiceFee,
			&i.Tax,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBooking = `-- name: UpdateBooking :one
UPDATE bookings
SET status = $2, checkout_date = $3, checkin_date = $4
WHERE booking_id = $1
RETURNING booking_id, user_booking, homestay_booking, promotion_id, status, booking_date, checkin_date, checkout_date, number_of_guest, service_fee, tax
`

type UpdateBookingParams struct {
	BookingID    string    `json:"booking_id"`
	Status       string    `json:"status"`
	CheckoutDate time.Time `json:"checkout_date"`
	CheckinDate  time.Time `json:"checkin_date"`
}

func (q *Queries) UpdateBooking(ctx context.Context, arg UpdateBookingParams) (Booking, error) {
	row := q.db.QueryRowContext(ctx, updateBooking,
		arg.BookingID,
		arg.Status,
		arg.CheckoutDate,
		arg.CheckinDate,
	)
	var i Booking
	err := row.Scan(
		&i.BookingID,
		&i.UserBooking,
		&i.HomestayBooking,
		&i.PromotionID,
		&i.Status,
		&i.BookingDate,
		&i.CheckinDate,
		&i.CheckoutDate,
		&i.NumberOfGuest,
		&i.ServiceFee,
		&i.Tax,
	)
	return i, err
}
